name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render Deploy Hook
        uses: tyrrrz/action-http-request@master
        with:
          url: https://api.render.com/deploy/srv-cup7u81u0jms73bkgbqg?key=_JvLd0v-TBg
